Сетка каталога
htmlacademy-htmlcss/1459161-sedona-29 pull request #10
Opened 2020-10-02 13:49 UTC by yalushevam

2020-10-02 19:52 UTC, mouxez requested changes

2020-10-02 19:52 UTC, mouxez commented on css/style.css
> +    background: #F2F2F2;
цвет нужно положить в переменную

2020-10-02 19:52 UTC, mouxez commented on css/style.css
> +    box-shadow: 0px 5px 15px rgba(0, 1, 1, 0.2);
тоже самое
цвет в var

2020-10-02 19:52 UTC, mouxez commented on css/style.css
>  body {
у боди нужно разобраться со стилями по тэгу и классу

2020-10-02 19:52 UTC, mouxez commented on css/style.css
>  .hotel-list-item {
тут нужно пересмотреть использование гридов

2020-10-03 15:45 UTC, yalushevam commented
Пока самое удачное что получилось разложить

2020-10-03 18:32 UTC, mouxez requested changes

2020-10-03 18:32 UTC, mouxez commented on catalog.html
> +                        <div class="hotel-photo"><img src="img/amara-hotel.jpg" width="135" height="90" alt="Фото гостиницы"></div>
вот тут нужно поправить.
фото отеля - это тоже ссылка, которая ведёт туда же, куда и ссылка заголовка отеля.
нужно картинку сделать ссылкой везде

2020-10-03 18:32 UTC, mouxez commented on catalog.html
> +                    <li><a href="">Информация</a></li>
пожалуйста, создай страницу blank.html, которая будет содержать просто строку с текстом "Этот раздел сайта находится в разработке ! Для перехода на главную, нажмите по этой надписи." и слова последние сделай ссылкой на index.html
такой вариант на лекции озвучивался, замени все пустые href="" на href="blank.html"

2020-10-05 05:16 UTC, mouxez approved these changes

2020-10-05 05:16 UTC, mouxez commented on catalog.html
> +                <h1> class="visually-hidden">Поиск гостиницы</h1>
тут тэг h1 нужно поправить - проверь, как он закрывается

2020-10-05 05:16 UTC, mouxez commented on catalog.html
> +                        <a href="blank.html"><img class="hotel-photo" src="img/amara-hotel.jpg" width="135" height="90" alt="Фото гостиницы"></a>
тут такая штука происходит - ссылка а, внутри которой находится имг, выходит за границы изображения (нужно исправить)
из-за этого кликнуть можно и за пределами изображения. плюс ссылки сливаются друг с другом и при переходе с одного изображения на другое пользователь не понимает, что ссылка изменилась

2020-10-05 05:16 UTC, mouxez commented on catalog.html
> +                        <a href="blank.html"><img class="hotel-photo" src="img/amara-hotel.jpg" width="135" height="90" alt="Фото гостиницы"></a>
![Screenshot 2020-10-05 at 08 08 58](https://user-images.githubusercontent.com/48134013/95042409-74fc4f00-06e2-11eb-87c7-4dd81b383428.png)

2020-10-05 05:16 UTC, mouxez commented on catalog.html
> +                        <a href="blank.html"><img class="hotel-photo" src="img/amara-hotel.jpg" width="135" height="90" alt="Фото гостиницы"></a>
красным выделил границы ссылки и они же являются кликабельными, хотя не должны

2020-10-05 05:16 UTC, mouxez commented on catalog.html
> +                        <a href="blank.html"><img class="hotel-photo" src="img/amara-hotel.jpg" width="135" height="90" alt="Фото гостиницы"></a>
![Screenshot 2020-10-05 at 08 14 03](https://user-images.githubusercontent.com/48134013/95042493-c0166200-06e2-11eb-8fa2-8355dd2c8ba2.png)

2020-10-05 05:16 UTC, mouxez commented on catalog.html
> +                        <a href="blank.html"><img class="hotel-photo" src="img/amara-hotel.jpg" width="135" height="90" alt="Фото гостиницы"></a>
на этом скриншоте видно, что название отеля и кнопки подробнее/забронировать выходят за пределы границ направляющих фото отеля. их нужно расположить так, чтобы они не выходили за предел области фото

2020-10-05 05:17 UTC, merged