Стилизация главной страницы
htmlacademy-htmlcss/1459161-sedona-29 pull request #4
Opened 2020-09-16 20:32 UTC by yalushevam

2020-09-16 20:37 UTC, yalushevam commented on index.html
>              <img src="https://via.placeholder.com/800x256" width="800" height="256" alt="Фото города 2">
Нужно обвернуть эту картинку в див, чтобы ее передвигать или возможно так?

2020-09-16 20:37 UTC, yalushevam commented on index.html
>              <img src="https://via.placeholder.com" width="800" height="256" alt="Фото города 1">
Вопрос один, по двум изображениям - Нужно обвернуть эту картинку в див, чтобы ее передвигать или возможно так?

2020-09-17 08:11 UTC, mouxez requested changes

2020-09-17 08:11 UTC, mouxez commented on index.html
> +            <h2 class="visually-hidden socials">Социальные сети</h2>
вот тут мне не понятно, зачем у спрятанного заголовка нужен класс socials

2020-09-17 17:48 UTC, yalushevam commented on css/style.css
> +.content-big {
Спасибо, прочитала)
Очень логично, но пока не получается всем такие имена задать

2020-09-17 17:50 UTC, yalushevam commented on css/style.css
> +/* Variables */
а возможно, что поменяв этот цвет и цвет шрифта нужно менять?

2020-09-18 05:36 UTC, mouxez commented on css/style.css
> +/* Variables */
да, возможно, для этого заведи brand-font-color

2020-09-18 10:22 UTC, mouxez approved these changes

2020-09-18 10:23 UTC, merged