Сетка (грид на главной)
htmlacademy-htmlcss/1459161-sedona-29 pull request #7
Opened 2020-09-24 08:44 UTC by yalushevam

.

2020-09-24 09:45 UTC, mouxez requested changes

2020-09-24 09:45 UTC, mouxez commented on css/style.css
> +.features-list {
в этом задании нужно сделать сетку главных блоков страницы максимально близкой к макету.
![Screenshot 2020-09-24 at 12 40 20](https://user-images.githubusercontent.com/48134013/94128692-1d98ec00-fe63-11ea-8cf0-5c0b6ff89f56.png)

2020-09-24 09:45 UTC, mouxez commented on css/style.css
> +.features-list {
для этого:
- сделай размер страницы сайта как в ТЗ - 1200рх
- расположи центральную сетку так, чтобы было 4 ряда по 2/3/2/3 блока внутри (как на скрине)
- задай им размеры, чтобы они примерно соответствовали макету
- текст не надо трогать, только блоки

2020-09-24 09:45 UTC, mouxez commented on css/style.css
> +.features-list {
примерно должно быть так (но без позиционирования текста):
![Screenshot 2020-09-24 at 12 44 08](https://user-images.githubusercontent.com/48134013/94129167-b6c80280-fe63-11ea-95e4-9703bb3e2544.png)

2020-09-24 09:46 UTC, mouxez commented on css/style.css
> +.features-list {
Информация:
На этом этапе от студентов требуется создать только сетку, без окончательной стилизации. Размеры блоков и расстояния между ними, должны быть очень близкими (с минимальной разницей) к размерам на макете.

2020-09-25 05:48 UTC, yalushevam commented on css/style.css
> +}
не очень уверена, можно ли указать расположение, а потом еще в следующем создать колонки, получается , что в сетке есть сетка
но теперь расположение выглядит лучше визуально

2020-09-25 15:04 UTC, mouxez requested changes

2020-09-25 15:04 UTC, mouxez commented on index.html
> +                        <h3 class="features-name">Жильё</h3>
а это макет
![Screenshot 2020-09-25 at 17 59 45](https://user-images.githubusercontent.com/48134013/94282786-e86ec580-ff58-11ea-9ae0-a1abf60e55df.png)

2020-09-25 15:04 UTC, mouxez commented on index.html
> +                    <h2 class="content-name"> Настоящий городок </h2>
у этого ряда первый блок цвет фона синий, блок с картинкой на фоне не должен иметь свой background-color
![Screenshot 2020-09-25 at 18 00 27](https://user-images.githubusercontent.com/48134013/94282933-148a4680-ff59-11ea-8a40-604a3f5d401f.png)

2020-09-27 11:04 UTC, yalushevam commented on css/style.css
> +    margin: 0 auto;
отступ в списках не убирается, я не в том месте поставила?

2020-09-27 14:29 UTC, mouxez commented on css/style.css
> +}
в принципе беды в этом нет никакой, ок

2020-09-27 14:35 UTC, mouxez approved these changes

2020-09-27 14:35 UTC, mouxez commented on css/style.css
> +    margin: 0 auto;
используй такую конструкцию, чтобы отслеживать выпадающие блоки или не понятные места на странице, но удаляй после работы перед коммитом. конструкцию нужно вставить в стилейвой файл и увидишь, что произойдёт
*, *::before, *::after {
  background-color: rgba(255, 0, 0, 0.1);
}

2020-09-27 14:35 UTC, mouxez commented on css/style.css
> +    margin: 0 auto;
так же для анализа расположения и стилей используй инструменты разработчика (F12 на виндоус)

тут поробнее:
https://youtu.be/LDJMfzTlkSI

2020-09-27 14:35 UTC, merged